version: '3.3'
services:
  mysql:
    container_name: empresta-db  # Container name
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.db
    volumes:
      - ./db_data/mysql:/var/lib/mysql
      - ./db_data/pgsql:/var/lib/postgresql
      - ./db_data/maria:/var/lib/mariadb
      - ./db_data/redis:/var/lib/redis
    ports:
      - '3308:3306'
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: empresta
      MYSQL_PASSWORD: empresta
      MYSQL_DATABASE: empresta
  server:
    container_name: empresta-api  # Container name
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: 'server/server:latest'
    volumes:
      - ./src:/server/src
      - ./dist:/server/dist
    ports:
      - '8081:8081'
      - "9222:9222" # debug port node for inspect-brk
    links:
      - mysql:mysql
    depends_on:
      - mysql
    stdin_open: true
    tty: true
